client_config_backend: settings
client_config:
  client_id: 570995719774-np1kb1sfashta07c199avi1ca84q5akm.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file